baseURL = "https://heartbees.github.io/"
languageCode = "zh-cn"
hasCJKLanguage = true
title = "Jimlynn"
theme = "PaperMod"


[params]

author = "小香猪"

description = "记录AI探索、技术学习与生活感悟"


defaultTheme = "auto"


# 评论
comments = true


# 文章功能

ShowPostNavLinks = true

ShowArchiveButton = true

ShowReadingTime = true

ShowWordCount = true

ShowBreadCrumbs = true

ShowPostSummary = true


# 首页封面

images = ["/images/cover.jpg"]

ShowHomeCover = true



# 首页介绍

Title = "Jimlynn的数字花园"

Content = """
记录AI探索、技术折腾与生活碎片。

在这里分享我的学习过程、工具体验和个人思考。
"""


# 菜单

[menu]

[[menu.main]]

identifier="about"

name="关于"

url="/about/"

weight=1


[[menu.main]]

identifier="posts"

name="博客"

url="/posts/"

weight=2



# URL

[permalinks]

posts="/posts/:title/"


# markdown

[markup.goldmark.renderer]

unsafe=true


[markup.highlight]

style="github"



# 搜索

[outputs]

home=["HTML","RSS","JSON"]



# Waline

[params.waline]

enable=true

serverURL="https://jimlynn.vercel.app"

pageview=true